<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>fasmdll_managed</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net20</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Microsoft.VisualC" />
    <Reference Include="System.Data">
      <HintPath>../../../../.dotnet/shared/Microsoft.NETCore.App/8.0.30/System.Data.dll</HintPath>
    </Reference>
    <Reference Include="System.Xml">
      <HintPath>../../../../.dotnet/shared/Microsoft.NETCore.App/8.0.30/System.Xml.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>