[package]
name = "pqr-inject"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
pqr-mem = { path = "../pqr-mem" }
pqr-asm = { path = "../pqr-asm" }
iced-x86 = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
